version: '3.3'

services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        restart: unless-stopped
        expose:
            - 8080
        volumes:
          - "./data.db:/app/data.db"